### ISSUE TITLE
Slow loading time

### ISSUE THREAD

**Issue by davistan** [NativeScript/nativescript-sdk-examples-ng#106]
Hi, I'm just testing this app out by cloning and running it on my device. The APK is 19.8 Mb and takes about 8 seconds to show the main view.

I tried running with `--release` flag and the APK is 19.7 Mb (0.1 Mb difference) and loading time does not improve.

Anything that I missed out?

Also, just some suggestion in the readme file.

`git clone --depth 1 git@github.com:NativeScript/nativescript-sdk-examples-ng.git`
should change to:
`git clone --depth 1 https://github.com/NativeScript/nativescript-sdk-examples-ng.git`

**Comment by valentinstoychev** [comment]
Hey @davistan - the size of the app is due to the large amount of pages and images in the app (~170 pages).

About the loading time - yes you are correct and we are putting a lot of efforts focused on improving *drastically* the loading time of this application - especially on Android. Our target for this app is to load between 1 and 2 seconds . We already have a POC internally that optimizes this and we are in a process of enabling it.

We have several efforts running together - both inside the core framework and in the Angular SDKs that will help us achieve this in the next several weeks - our target date is with the 2.5 release.


Please keep us posted on any other improvements you would like to see.

**Comment by davistan** [comment]
Cool! I saw the NS 2.4 release notes for the V8 symbols removal and to gauge the performance difference, hence I tried on this project.

Anyway, good to know that's in the pipeline and will wait for updates from you guys.

Keep it up!

**Comment by snekbaev** [comment]
Hi @valentinstoychev,

At the moment I'm working on a small app for personal use which is sort of an evaluation of NS. App has 2 views, it sends, reads and receives smses, has a listview, uses several third-party and own plugins. Current apk file is 23.7MB, there might be some problem with it https://github.com/NativeScript/nativescript-cli/issues/2269, but so we can skip this one for now.

When apk file is opened and then the tns_modules folder, it becomes quite obvious that AngularJS related modules are the largest one. The start up time (splashscreen to main view) was about 4-5 seconds, but after adding a couple of plugins it became around 6, which is a **lot** for such simple application.

Thus I'm having following thoughts and would really appreciate if you could validate them:

1) everything that is possible to do with Angular should be possible to implement via core API and still use Typescript. Yes, Angular provides some nice built-in things, however in the context of NS (and mobile development) those might not be necessary, moreover, could be harmful: ngFor is not virtualized, personally ran into ListView problems while using DatePipe transformation (quick scrolling wasn't smooth) and the solution was to preprocess all the data and use ListView to just output. Some stackoverflow posts suggest that not using Angular quite nicely improved the start-up time.

2) potentially more overhead while using Angular at run-time which could introduce occasional minor lags. I do get those with my current implementation, however I will yet need to re-implement another version of it without Angular to compare, so this one is more of a guess, yet common sense says that the less JS engine needs to handle the better things are :)

3) output package file size, start-up time and the first "just in time compilation". First one is quite obvious: the smaller - the better. Start-up time is a big one in here. I expect my app to start under three seconds, ideally under two, but waiting six seconds on Nexus 5 a bit of a pain. Also I noticed that the first time I trigger, say navigation, it takes longer to perform the action. Then occasionally when navigation is triggered instead of going to page B and showing the activity indicator app freezes for around a second and then shows the Page B with the data already loaded.

4) UX over developer comfort: I'd rather give-up Angular and write a reasonable amount of extra boilerplate code than sacrifice a) run-time performance b) start-up time c) app package size

What do you think of these in the light of expected performance optimizations coming in 2.5.0? Should I switch to just core API + TS or am I over-exaggerating the Angular's impact and doing a lot of guess work? :)

Thank you!

**Comment by felipewom** [comment]
Hello, I've tested my project and I am experiencing the same issues, startup really slow about 6 seconds, refreshing flex box layout items with ngfor takes about 4 seconds with simple array populated with 10 items... And the most terrible is navigating to another page and then navigate back it takes 5..6 seconds each navigation transition  and sometimes it freezes... 
I am using NS 2.5.0 Angular and typescript testing on Android target 5.1.1 galaxy tab 4, any suggestions to improve performance?

**Comment by Dutchboy** [comment]
@felipewom Same here.... Or no, even worse.... I've just installed an app of my own... 10 to 13 seconds... So, I guessed I'd do the LazyNinjas.... Both on release mode.... Both over 10 seconds.... my phone is not slow.... So, I guess I'm doing something wrong here....? Any thoughts?

**Comment by Dutchboy** [comment]
@valentinstoychev Hi Valentin!... You've mentioned somewhere here above that your team was working on an improvement of the loading time... And after that, your colleague @sis0k0  Stanimira wrote an article about Lazy Loading, which I follow in my sources..... How are your thoughts about the loading times I mentioned here above?? What do I do wrong??

**Comment by luchillo17** [comment]
@Dutchboy I'm a bit late to the party but let me share a few things:
- If i start a project with the angular template i get 10~11 secs load time consistently.
- If i install the `android-snapshot` plugin it goes down to 6~7 secs load time.
- If i install the `nativescript-dev-webpack` package it goes down to 4~5 secs (Please note that this and the previous one are incompatible with each other).

Please note that:
- 4~5 secs is the best i have achieved even after uglifying the app (with `--uglify` flag).
- This is the starter angular template, doesn't make sense that an empty app takes 10~11 secs right after creating the app.
- I feel like it's damn slow after comparing it to React Native 2~3 secs max load time (which already comes with React included, my only complain is that i cannot make it work with typescript).

**Comment by weibingbing5101** [comment]
下载完成后，执行tns run ios报这个错误
Unable to apply changes on device: 695247EC-9384-4827-8C47-D8FD81125BEF. Error is: nativescript-googlemaps has Podfile and you don't have Cocoapods installed or it is not configured correctly. Please verify Cocoapods can work on your machine..

tns install 报如下错误
Error: ENOENT: no such file or directory, open '/Users/weiweibing/Desktop/nativescript-sdk-examples-ng/node_modules/node-pre-gyp/package.json'
Error: ENOENT: no such file or directory, open '/Users/weiweibing/Desktop/nativescript-sdk-examples-ng/node_modules/node-pre-gyp/package.json'

请问如何解决

**Comment by NickIliev** [comment]
@Dutchboy as an update on that topic let me say that with the current version of NativeScript (3.4.0) we have a lot of optimizations including improved loading time with Webpack, uglify, snapshots (Android) and AOT (Angular).

Updated instructions on how to bundle with Webpack with ^3.4.x canb e found [here](https://docs.nativescript.org/best-practices/bundling-with-webpack)
