### ISSUE TITLE
how to change color of header of date-picker?

### ISSUE THREAD

**Issue by SumanSingh4** [NativeScript/nativescript-sdk-examples-ng#177]
I want to change color of header and selected date circle of date picker from blue to orange.
Any one have any idea how to do it??

![screen shot 2017-04-19 at 4 08 09 pm](https://cloud.githubusercontent.com/assets/25900614/25176020/7466b1fa-251a-11e7-8655-a1a1062a2d0f.png)

**Comment by tsonevn** [comment]
Hi @SumanSingh4, 
While using the default DatePicker component, you could change several style properties. For example, you could change the `background-color` or `color`. For further info about the available properties for the DatePicker component, you could review the [api-reference](http://docs.nativescript.org/api-reference/classes/_ui_date_picker_.datepicker.html).
Sample:
```
<GridLayout class="page">
    <DatePicker backgroundColor="red" color="green" ></DatePicker>
</GridLayout>
```

Please let me know if I am missing something or in case you are using some external plugin instead of the default DatePicker component.
